#language: generic
language: node_js

sudo: required
services:
  - docker

before_install:
  - docker build -t actnky/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true actnky/docker-react npm run test
#  - docker run actnky/docker-react npm run test -- --coverage

#deploy:
#  edge: true
#  provider: elasticbeanstalk
#  region: "eu-west-2"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-eu-west-2-651236344265"
#  bucket_path: "docker-react"
#  on:
#    branch: master

#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: 
#    secure: "$AWS_SECRET_KEY"

notifications:
  slack: ardacetinkaya:gix5eD7jtdAHzj60LP3ZeZlt
    on_success: always
    on_failure: always
    on_pull_requests: always
    
#Updated travis.yml v6.4
